#### 3.1 The world as floating-point numbers 
- 신경망 안에서 정보처리는 결국 부동소수점 수로 나타내므로 우리가 원하는 실제 데이터를 신경망 연산이 가능하도록 인코딩해야 하고 처리 후 나온 결과값을 해석 가능하거나 사용 가능할 수 있도록 디코딩해야 한다. 
- Deep Neural network 은 보통 여러 단계를 거쳐서 데이터 변환을 학습한다. 그래서 각 단계 사이의 일부 변환된 데이터들은 중간 단계를 표현하는 연속적인 흐름으로 생각할 수 있다. 
- 데이터의 처리와 저장을 위해서 pytroch는 tensor라는 기본 자료 구조를 제공한다. Deep learning에서 tensor은 임의의 차원을 가진 vector, matrix의 일반화된 개념으로 보면 된다. tensor을 multidimensional array이라고도 부른다. 


#### 3.2 Tensors: Multidimentional array 

In [3]:
# 3.2.1 
# From Python lists to Pytorch tensors 
a = [1.0, 2.0, 1.0]
a[0]
a[1]
a[2]
a

[1.0, 2.0, 1.0]

In [8]:
# 3.2.2 
#Constructin out frist tensors 
import torch 
a = torch.ones(3)
a[1]

float(a[1])
a[2] = 2.0
a

tensor([1., 1., 2.])

In [12]:
# 3.2.3 
# The essence of tensors 

points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [13]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [15]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [20]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points[0]
points[1]
points[2]


tensor([2., 1.])

In [21]:
points.shape

torch.Size([3, 2])

In [23]:
points.size()

torch.Size([3, 2])

In [24]:
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [26]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [27]:
points[0, 1]

tensor(1.)

In [28]:
points[0]

tensor([4., 1.])

In [36]:
# 3.3 
# Indexing tensors 
some_list = list(range(6))
some_list[:]
some_list[1:4]
some_list[1:]
some_list[:4]
some_list[:-1]
some_list[1:4:2]


[1, 3]

In [45]:
points[1:]
points[1:, :]
points[1:, 0]
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [48]:
# 3.4 
# Named tensors 
img_t = torch.randn(3, 5, 5) 
weights = torch.tensor([0.2126, 0.7152, 0.0722])
batch_t = torch.randn(2, 3, 5, 5)
batch_t

tensor([[[[-1.4018e-01, -1.1655e+00,  1.2350e+00, -2.1291e+00, -8.7423e-01],
          [-1.4542e+00, -1.0348e+00, -4.1871e-01, -1.4276e+00, -1.8865e-01],
          [-9.8741e-01, -1.2642e+00,  8.1591e-01,  2.1995e-01,  4.4798e-01],
          [ 1.7669e+00,  7.2655e-01, -2.2878e+00,  1.2280e+00,  2.4703e+00],
          [ 1.3505e+00,  3.8006e-02,  2.7383e-01, -5.4026e-01, -2.6950e-01]],

         [[-1.5744e-01, -6.7220e-02,  7.9991e-01,  2.6635e-01,  9.1026e-02],
          [ 5.1894e-02, -8.3172e-01,  7.0690e-01,  8.4076e-01, -7.1635e-01],
          [ 9.2175e-01, -2.2105e-01,  1.2132e+00,  4.5610e-01,  1.4139e+00],
          [-1.2577e+00, -5.4609e-01, -1.6843e-01,  1.3550e+00, -1.6231e-01],
          [ 8.2095e-02,  1.2978e+00, -1.9142e+00, -1.0515e+00,  2.4508e-01]],

         [[-7.8844e-02,  1.3536e-01,  2.8687e-01,  2.2111e+00, -3.2386e-02],
          [ 1.8968e+00,  7.3387e-02,  1.6552e+00, -5.0203e-01, -7.9461e-01],
          [-6.2130e-01, -7.2067e-01, -8.2501e-01,  5.2617e-01,  9.1256e-

In [50]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape


(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [52]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [57]:
img_weights = img_t * unsqueezed_weights
batch_weights = batch_t * unsqueezed_weights
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, img_gray_weighted.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([5, 5]), torch.Size([3, 1, 1]))

In [62]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=["channels"])
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [63]:
img_named = img_t.refine_names(..., "channels", "rows", "columns")
batch_named = batch_t.refine_names(..., "channels", "rows", "columns")
print("img_named", img_named.shape, img_named.names)
print("batch_named", batch_named.shape, batch_named.names)


img_named torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch_named torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [65]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [68]:
gray_named = (img_named * weights_aligned).sum("channels")
gray_named
gray_named.shape, gray_named.names


(torch.Size([5, 5]), ('rows', 'columns'))

#### 3.5 Tensor elements type 


In [70]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)
double_points.dtype, short_points.dtype

(torch.float64, torch.int16)

In [72]:
double_points = torch.zeros(10, 2).double()
short_points = torch.zeros(10, 2).short()
double_points.dtype, short_points.dtype

(torch.float64, torch.int16)

In [73]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.zeros(10, 2).to(torch.short)
double_points.dtype, short_points.dtype

(torch.float64, torch.int16)

In [75]:
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.to(torch.short)
points_64 * points_short 

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [76]:
# 3.6 
# The tensor API 
a = torch. ones(3, 2)
a_t = torch.transpose(a, 0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [78]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [79]:
# 3.7 
# Tensor : Scenic views of stroage 
# 3.7.1 
# Indexing into storage 
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage._TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [86]:
points_storage = points.storage()
points_storage[0]
points.storage()[1]


1.0

In [90]:
points =torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0]=2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [92]:
# 3.7.2 
# Modifying stored values : In-place operations 
a = torch.ones(3, 2)
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [103]:
# 3.8 
# Tensor metadata : size, offset and stride 
# 3.8.1 
# Views of another tensor's storage 
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_points = points[1]
second_points.size()
second_points.storage_offset()
second_points.stride()
points.stride()


tensor([5., 3.])

In [105]:
second_point = points[1]
second_point.size()
points.stride()

(2, 1)

In [114]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [115]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [118]:
# 3.8.2 
# Transposing without copying
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [119]:
id(points.storage()) == id(points_t.storage())

True

In [122]:
points.stride(), points_t.stride()

((2, 1), (1, 2))

In [127]:
# 3.8.3 
# Transposing in higher dimensions 
somt_t = torch.ones(3, 4, 5)
#somt_t
transpose_t = somt_t.transpose(0, 2)
somt_t.shape, transpose_t.shape
somt_t.stride(), transpose_t.stride()

((20, 5, 1), (1, 5, 20))

In [129]:
# 3.8.4 
# Contiguous tensors 
poitns.is_contiguous(), transpose_t.is_contiguous()

(True, False)

In [142]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
# points_t, points_t.storage()
points_t.stride()
points_t_cont = points_t.contiguous()
points_t_cont.shape
# points_t.shape

# points_t_cont.stride()


torch.Size([2, 3])